### ISSUE TITLE
Can't get ART to work with 0.6

### ISSUE THREAD

**Issue by 0x80** [brentvatne/react-native-art-example#3]
Has something changed with 0.6? I can't get it to work.

I have included the ART project and library and the xcode project builds fine. But as soon as I require the VectorWidget module in my javascript I get this error in my app screen:

**Application MyApp has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.**

**Comment by brentkirkland** [comment]
same

**Comment by brentkirkland** [comment]
Use ReactNativeART not ReactIOSART

**Comment by 0x80** [comment]
Thanks. I had figured it out. Didnt' know this issue was stil open.
